##Login
url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
username=Admin
password=admin123
successlogin=Dashboard


##Recruitment

firstName=Kanishkar
lastName=Ravi
email=kansishkar@gmail.com

